spring.application.name=BillingAuthApplication
server.port=${PORT:8080}

# ================= DATABASE =================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false


# ================= BREVO API =================
brevo.api.key=${BREVO_API_KEY}

# SPEED OPTIMIZATION
spring.main.lazy-initialization=true

# ================= JWT =================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ================= LOGGING =================
logging.level.org.springframework=ERROR